# This version of config.mak was generated by:
# ./configure --target=x86_64-linux-musl --disable-shared --prefix=/home/booga/vexapay/otsos2/libc/musl-install CC='clang --target=x86_64-linux-musl' CFLAGS='-O2 -g -fno-pic'
# Any changes made here will be lost if configure is re-run
AR = llvm-ar
RANLIB = llvm-ranlib
ARCH = x86_64
SUBARCH = 
ASMSUBARCH = 
srcdir = .
prefix = /home/booga/vexapay/otsos2/libc/musl-install
exec_prefix = $(prefix)
bindir = $(exec_prefix)/bin
libdir = $(prefix)/lib
includedir = $(prefix)/include
syslibdir = /lib
CC = clang --target=x86_64-linux-musl
CFLAGS = -O2 -g -fno-pic
CFLAGS_AUTO = -pipe -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -w -Wno-pointer-to-int-cast -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith -Werror=int-conversion -Werror=incompatible-pointer-types -Qunused-arguments -Waddress -Warray-bounds -Wchar-subscripts -Wduplicate-decl-specifier -Winit-self -Wreturn-type -Wsequence-point -Wstrict-aliasing -Wunused-function -Wunused-label -Wunused-variable
CFLAGS_C99FSE = -std=c99 -nostdinc -ffreestanding -fexcess-precision=standard -frounding-math -fno-strict-aliasing -Wa,--noexecstack
CFLAGS_MEMOPS = 
CFLAGS_NOSSP = -fno-stack-protector
CPPFLAGS = 
LDFLAGS = 
LDFLAGS_AUTO = -Wl,--sort-section,alignment -Wl,--sort-common -Wl,--gc-sections -Wl,--hash-style=both -Wl,--no-undefined -Wl,--exclude-libs=ALL -Wl,--dynamic-list=./dynamic.list
CROSS_COMPILE = x86_64-linux-musl-
LIBCC = -lgcc -lgcc_eh
OPTIMIZE_GLOBS = 
ALL_TOOLS =  obj/musl-clang obj/ld.musl-clang
TOOL_LIBS = 
ADD_CFI = yes
MALLOC_DIR = mallocng
SHARED_LIBS =
WRAPCC_CLANG = $(CC)
