#!/usr/bin/env python3
import argparse
import os
import subprocess
import sys


DEFINED_TYPES = set("ABCDGRSTVW")


def c_escape(text: str) -> str:
    return text.replace("\\", "\\\\").replace("\"", "\\\"")


def collect_symbols(nm: str, objects: list[str]) -> list[str]:
    symbols: dict[str, None] = {}
    cmd = [nm, "-P", "--defined-only", "--extern-only", *objects]
    result = subprocess.run(cmd, check=False, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, text=True)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"{nm} failed")
    for line in result.stdout.splitlines():
        parts = line.split()
        if not parts or line.endswith(":") or len(parts) < 2:
            continue
        if len(parts) >= 3 and parts[0].endswith(":"):
            name = parts[1]
            sym_type = parts[2]
        else:
            name = parts[0]
            sym_type = parts[1]
        if sym_type[:1].upper() not in DEFINED_TYPES:
            continue
        if name.startswith("kofo_kernel_symbol"):
            continue
        symbols.setdefault(name, None)
    return sorted(symbols)


def write_ksymtab(path: str, symbols: list[str]) -> None:
    out_dir = os.path.dirname(path)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(path, "w", encoding="ascii") as f:
        f.write("/*\n")
        f.write(" * Generated by tools/kofo_ksymtab.py. Do not edit.\n")
        f.write(" */\n\n")
        f.write("#include <kernel/kofo.h>\n\n")
        for index, name in enumerate(symbols):
            f.write(f"extern char kofo_ksym_{index}[] ")
            f.write(f"__asm__(\"{c_escape(name)}\");\n")
        f.write("\n")
        if not symbols:
            f.write("const kofo_kernel_symbol_t kofo_kernel_symbols[1] = {\n")
            f.write("\t{ NULL, NULL }\n")
            f.write("};\n")
            f.write("const u32 kofo_kernel_symbol_count = 0;\n")
            return
        f.write("const kofo_kernel_symbol_t kofo_kernel_symbols[] = {\n")
        for index, name in enumerate(symbols):
            f.write(f"\t{{ \"{c_escape(name)}\", ")
            f.write(f"(const void *)kofo_ksym_{index} }},\n")
        f.write("};\n")
        f.write(f"const u32 kofo_kernel_symbol_count = {len(symbols)};\n")


def parse_args(argv: list[str]) -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="generate KOFO kernel symbol table from kernel objects")
    ap.add_argument("objects", nargs="+")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument("--nm", default="llvm-nm")
    return ap.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    try:
        symbols = collect_symbols(args.nm, args.objects)
        write_ksymtab(args.output, symbols)
    except (OSError, RuntimeError) as exc:
        print(f"kofo_ksymtab: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
