# Build-time configuration only.
# Runtime configuration lives in ../config/hives/*.hive and cmseed.

[os]
release = "2.3.3"

[libc]
enabled = true
type = "musl"

[disk.pata]
enabled = false

[kshell]
enabled = true

[kshell.commands.help]
enabled = true

[kshell.commands.clear]
enabled = true

[kshell.commands.echo]
enabled = true

[kshell.commands.drm_switch]
enabled = true

[kshell.commands.exit]
enabled = true
